import LocalizedStrings from "react-localization";

let strings = new LocalizedStrings({
  en: {
    apptitle: "MOI",
    paci: " تكامل",
    searchhint: "Enter Civil ID",
    homeview: "Default",
    zoomin: "Zoom In",
    zoomout: "Zoom Out",
    addresses: "Addresses",
    persons: "Persons",
    switchlayer: "Switch Layer",
    pagination: "Show result from {0} - {1}",
    updateresultonmap: "Update result on map extent change",
    backtosearchresult: "Back to results",
    searchinthisplace: "Search in this place",
    language: "Language",
    loadingtext: "Loading Kuwait Finder Application...",
    quicksearch: "Quick Search",
    clear: "Clear",
    search: "Search",
    back: "Back",
    governorates: "Governorates",
    neighborhoods: "Areas",
    blocks: "Blocks",
    streets: "Streets",
    parcels: "Parcels",
    mylocalion: "My Location",
    whatishere: "What's here?",
    centerhere: "Center map here",
    addtofavorites: "Add to favorites",
    noresult: "No result found",
    error: "Error",
    parcelpacinumber: "Parcel PACI Number ",
    all: "All",
    today: "Today",
    yesterday: "Yesterday",
    beforeYesterday: "Before yesterday",
    feedback: "Feedback",
    favorite: "Favorite",
    favorites: "Favorites",
    searchfavorites: "Search favorites",
    delete: "Delete",
    edit: "Edit",
    share: "Share",
    traffic: "Traffic",
    fast: "Fast",
    slow: "Slow",
    funerals: "Funerals",
    years: " Years",
    menu: "Menu",
    categories: "Categories",
    emptyfuneral: "No funerals found for this day",
    emptyfavorites: "You have no favorites",
    emptyhistory: "Your search history is empty",
    showmap: "Show Map",
    showresult: "Hide Result",
    map: "Map",
    results: "Results",
    copyrights:
      "The Public Authority for Civil Information\nCopyright © 2013 - 2019",
    darkmode: "Dark Mode",
    complians: "Complains",
    addressaatcher: "Address Matcher",
    joblist: "Job List",
    insertjob: "Insert Jobs",
    lastupdate: "Last update",
    createdby: "Created by",
    org: "Establishment",
    jobhistory: "Job History",
    showdetails: "Show Details",
    takeaction: "Take Action",
    establishment: "Establishment",
    searchinestablishments: "search in establishments",
    nodataforestablishment: "No available data for this establishment",
    attachments: "Attachments",
    send: "Send",
    form: "Form",
    done: "Done",
    dropzoneText:
      "Drag and drop the images here or click a 3 images maximum, the image size is 5MB",
    attachedimages: "Attached images",
    systemidentical: "System identical",
    systemexistance: "System existance",
    status: "Status",
    theaddress: "The Address",
    units: "The units",
    parcelunitnumber: "parcel unit number",
  },
  ar: {
    apptitle: "MOI",
    paci: " تكامل",
    searchhint: "أدخل الرقم المدني",
    homeview: "خريطة كاملة",
    zoomin: "تصغير الخريطة",
    zoomout: "تكبير الخريطة",
    switchlayer: "تغيير الطبقة",
    addresses: "عناوين",
    persons: "أشخاص",
    pagination: "عرض النتائج من‏ {0} -‏ {1}‏",
    updateresultonmap: "تحديث النتائج عند تحريك الخريطة",
    backtosearchresult: "عودة إلي النتائج",
    searchinthisplace: "ابحث في هذه المنطقة",
    language: "اللغه",
    loadingtext: "جارى تحميل كويت فايندر...",
    quicksearch: "البحث سريع",
    clear: "مسح",
    search: "بحث",
    back: "عودة",
    governorates: "المحافظات",
    neighborhoods: "المناطق",
    blocks: "القطع",
    streets: "الشوارع",
    parcels: "القسائم",
    mylocalion: "موقعي الحالي",
    whatishere: "ماذا هنا؟",
    centerhere: "توسيط الخريطة هنا",
    addtofavorites: "أضف للمفضلة",
    noresult: "لا توجد نتائج ",
    error: "حدث خطأ",
    parcelpacinumber: "الرقم الآلي للقسيمة ",
    all: "الكل",
    today: "اليوم",
    yesterday: "الأمس",
    beforeYesterday: "قبل الأمس",
    feedback: "إرسال ملاحظة",
    favorite: "المفضله",
    favorites: "المفضلات",
    searchfavorites: "ابحث في المفضلات",
    delete: "حذف",
    edit: "تعديل",
    share: "مشاركة",
    traffic: "حركة المرور",
    fast: "سريعة",
    slow: "بطيئة",
    funerals: "الوفيات",
    years: " عاماً",
    menu: "القائمة",
    categories: "الأقسام",
    emptyfuneral: "لا توجد وفيات لهذا اليوم",
    emptyfavorites: "لا توجد لديك مفضلات",
    emptyhistory: "لا توجد لديك عمليات بحث سابقة",
    showmap: "إظهار الخريطة",
    showresult: "إظهار النتائج",
    map: "الخريطة",
    results: "النتائج",
    copyrights:
      "جميع الحقوق محفوظة للهيئة العامة للمعلومات المدنية\n© 2013 - {0}",
    darkmode: "الوضع القاتم",
    complians: "الشكاوى",
    addressaatcher: " عنونه",
    joblist: " القائمة",
    insertjob: " ادخال طلبات",
    lastupdate: "آخر تحديث",
    createdby: "أنشئ بواسطة",
    org: "الجهة",
    jobhistory: "الاجراءات السابقة",
    showdetails: "عرض التفاصيل",
    takeaction: "إتخذ إجراء",
    establishment: "الجهات",
    searchinestablishments: "بحث في الجهات",
    nodataforestablishment: "لا توجد بيانات متوفرة للجهة",
    attachments: "المرفقات",
    send: "إرسال",
    form: "النموذج",
    done: "تم",
    dropzoneText:
      "قم بسحب وإسقاط الصور هنا أو إضغط بحد أقصى 3 صور حجم الصورة 5 ميجا بايت.",
    attachedimages: "الصور المرفوعة",
    systemidentical: "هل النظام موجود؟",
    systemexistance: "هل النظام متطابق؟",
    status: "الحالة",
    theaddress: "العنوان",
    units: "الوحدات",
    parcelunitnumber: "الرقم الآلي للوحدة",
  },
});
export default strings;
